#!/usr/bin/env bash

[ -r /etc/lsb-release ] && . /etc/lsb-release

if command -v toilet >/dev/null 2>&1; then
	toilet --gay "Vicharak"
fi

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
echo ""

echo "Welcome to $DISTRIB_DESCRIPTION ("$(uname -o)" "$(uname -r)" "$(uname -m)")"
echo ""
